const express = require('express');
const PDFDocument = require('pdfkit');
const { auth } = require('../middleware/auth');

const router = express.Router();

// Generate PDF report
router.post('/generate', auth, async (req, res) => {
  try {
    const { scanResult, certificate } = req.body;

    // Create PDF document
    const doc = new PDFDocument({
      size: 'A4',
      margins: { top: 50, bottom: 50, left: 50, right: 50 }
    });

    // Set response headers
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename=trustlock-report-${certificate.id}.pdf`);

    // Pipe PDF to response
    doc.pipe(res);

    // Header
    doc.fontSize(24).fillColor('#3B82F6').text('TrustLock', { align: 'center' });
    doc.fontSize(12).fillColor('#6B7280').text('Deepfake Detection Report', { align: 'center' });
    doc.moveDown(2);

    // Certificate Info
    doc.fontSize(16).fillColor('#111827').text('Certificate Information');
    doc.moveDown(0.5);
    doc.fontSize(10).fillColor('#374151');
    doc.text(`Certificate ID: ${certificate.id}`);
    doc.text(`Certificate Hash: ${certificate.hash}`);
    doc.text(`Timestamp: ${new Date(certificate.timestamp).toLocaleString()}`);
    doc.text(`Blockchain Block: ${certificate.blockIndex || 'Pending'}`);
    doc.moveDown(1.5);

    // Verdict Box
    const verdictColor = getVerdictColor(scanResult.result.verdict);
    doc.roundedRect(50, doc.y, 495, 80, 10).fillAndStroke(verdictColor + '20', verdictColor);
    doc.moveDown(0.5);
    doc.fontSize(14).fillColor(verdictColor).text(`Verdict: ${scanResult.result.verdict}`, { align: 'center' });
    doc.fontSize(20).fillColor(verdictColor).text(`${scanResult.result.deepfake_score}%`, { align: 'center' });
    doc.fontSize(10).fillColor('#6B7280').text(`Confidence: ${scanResult.result.verdict_confidence}`, { align: 'center' });
    doc.moveDown(2);

    // Analysis Summary
    doc.fillColor('#111827').fontSize(16).text('Analysis Summary');
    doc.moveDown(0.5);
    doc.fontSize(10).fillColor('#374151');
    doc.text(`Frames Analyzed: ${scanResult.result.frames_analyzed}`);
    doc.text(`Average Score: ${scanResult.result.analysis_summary.average_score}%`);
    doc.text(`Max Score: ${scanResult.result.analysis_summary.max_score}%`);
    doc.text(`Consistency: ${scanResult.result.analysis_summary.consistency}%`);
    doc.moveDown(1.5);

    // Detection Methods
    doc.fontSize(16).fillColor('#111827').text('Detection Methods Used');
    doc.moveDown(0.5);
    doc.fontSize(10).fillColor('#374151');
    const methods = [
      'Neural Network Analysis (EfficientNet)',
      'Face Boundary Detection',
      'Skin Texture Analysis',
      'Color Consistency Check',
      'Frequency Domain Analysis',
      'Compression Artifact Detection'
    ];
    methods.forEach((method, i) => {
      doc.text(`${i + 1}. ${method}`);
    });
    doc.moveDown(1.5);

    // Footer
    doc.fontSize(8).fillColor('#6B7280');
    doc.text('This report is generated by TrustLock AI-powered deepfake detection system.', { align: 'center' });
    doc.text('Certificate is cryptographically secured on blockchain.', { align: 'center' });
    doc.moveDown(0.5);
    doc.text(`Report generated on ${new Date().toLocaleString()}`, { align: 'center' });

    // Finalize PDF
    doc.end();

  } catch (error) {
    console.error('Report generation error:', error);
    if (!res.headersSent) {
      res.status(500).json({ message: 'Failed to generate report' });
    }
  }
});

function getVerdictColor(verdict) {
  const colors = {
    'AUTHENTIC': '#10B981',
    'LIKELY_AUTHENTIC': '#22C55E',
    'UNCERTAIN': '#F59E0B',
    'SUSPICIOUS': '#F97316',
    'LIKELY_DEEPFAKE': '#EF4444'
  };
  return colors[verdict] || '#6B7280';
}

module.exports = router;
